spring.application.name=banking-api

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_api
spring.datasource.username=gabriel
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
